#' Add sample annotations to QFeatures object
#'
#' @param qft A \code{QFeatures} object.
#' @param iColPattern Regular expression to be removed from the column
#'     names of \code{qft} to generate the sample names.
#' @param sampleAnnot \code{data.frame} with sample annotations. Must
#'     have at least columns named \code{sample} (which must contain
#'     all the sample names generated by removing the \code{iColPattern}
#'     from the column names of \code{qft}) and \code{group} (which contains
#'     the group assignment for each sample). Can also have a column named
#'     \code{batch}; in this case this will be used as a covariate in the
#'     limma model.
#' @param mergeGroups Named list defining groups to merge. Each entry of
#'     the list corresponds to a new group, and consists of a vector
#'     with the group names to merge.
#'
#' @return A \code{QFeatures} object with additional sample annotations.
#'
#' @examples
#' mqFile <- system.file("extdata", "mq_example", "1356_proteinGroups.txt",
#'                       package = "einprot")
#' samples <- c("Adnp_IP04", "Adnp_IP05", "Adnp_IP06",
#'              "Chd4BF_IP07", "Chd4BF_IP08", "Chd4BF_IP09",
#'              "RBC_ctrl_IP01", "RBC_ctrl_IP02", "RBC_ctrl_IP03")
#' ecol <- paste0("iBAQ.", samples)
#' qft <- QFeatures::readQFeatures(mqFile, ecol = ecol, name = "Intensity",
#'                                 sep = "\t", nrows = 25)
#' sampleAnnot <- data.frame(sample = samples,
#'                           group = gsub("_IP.*", "", samples))
#' qft <- addSampleAnnots(qft, iColPattern = "^iBAQ\\.",
#'                        sampleAnnot = sampleAnnot, mergeGroups = list())
#' SummarizedExperiment::colData(qft)  ## group information added to qft
#'
#' @export
#' @author Charlotte Soneson
#'
addSampleAnnots <- function(qft, iColPattern, sampleAnnot,
                            mergeGroups = list()) {
    .assertVector(x = qft, type = "QFeatures")
    .assertScalar(x = iColPattern, type = "character")
    .assertVector(x = sampleAnnot, type = "data.frame")
    .assertVector(x = mergeGroups, type = "list")
    stopifnot(all(c("sample", "group") %in% colnames(sampleAnnot)))
    if (length(mergeGroups) > 0) {
        .assertVector(x = names(mergeGroups), type = "character")
        if (is.null(names(mergeGroups)) || any(names(mergeGroups) == "") ||
            any(duplicated(names(mergeGroups)))) {
            stop("'mergeGroups' must be a named list, without duplicated names")
        }
        if (any(duplicated(unlist(mergeGroups)))) {
            stop("A given name can just be part of one merged group")
        }
    }
    stopifnot(all(!duplicated(sampleAnnot$sample)))


    ## Get sample ID by removing the iColPattern from the colnames
    cdn <- sub(iColPattern, "", colnames(qft)[[1]])
    qft$sample <- cdn

    if (!all(qft$sample %in% sampleAnnot$sample)) {
        stop("Some samples are missing from the sample annotation: ",
             paste(setdiff(qft$sample, sampleAnnot$sample), collapse = ", "))
    }

    qft$group_orig <- sampleAnnot$group[match(qft$sample, sampleAnnot$sample)]
    if ("batch" %in% colnames(sampleAnnot)) {
        qft$batch <- sampleAnnot$batch[match(qft$sample, sampleAnnot$sample)]
    }

    ## Define a new grouping based on the defined mergeGroups
    qft$group <- qft$group_orig
    for (nm in names(mergeGroups)) {
        qft$group[qft$group_orig %in% mergeGroups[[nm]]] <- nm
    }

    qft
}
