#' Assemble table with abundances of significant features
#'
#' Assemble table with abundances of features that are significant in at least
#' one comparison.
#'
#' @export
#' @author Charlotte Soneson
#'
#' @param testresList List of `data.frames` with test results, typically
#'     generated by \code{runTest()}.
#' @param abundancePrefix Character scalar giving the prefix for the
#'     columns in the test result tables that contain abundance information.
#'
#' @importFrom dplyr select filter starts_with contains if_any full_join
#'     matches everything
#'
makeAbundanceExport <- function(testresList, abundancePrefix) {
    .assertVector(x = testresList, type = "list")
    .assertScalar(x = abundancePrefix, type = "character")

    abundanceExport <- lapply(structure(names(testresList),
                                        names = names(testresList)), function(nm) {
        testresList[[nm]] %>% dplyr::select(c("pid", "showInVolcano",
                                              dplyr::starts_with(abundancePrefix)))
    })
    for (nm in names(abundanceExport)) {
        colnames(abundanceExport[[nm]])[colnames(abundanceExport[[nm]]) == "showInVolcano"] <-
            paste0("showInVolcano_", nm)
    }
    abundanceExport <- Reduce(function(...) dplyr::full_join(..., by = "pid",
                                                             suffix = c("", "__remove")),
                              abundanceExport) %>%
        dplyr::select(pid, dplyr::starts_with("showInVolcano"),
                      dplyr::matches("avg$"), dplyr::matches("sd$"),
                      dplyr::everything()) %>%
        dplyr::select(-dplyr::contains("__remove")) %>%
        dplyr::filter(dplyr::if_any(dplyr::starts_with("showInVolcano"), ~ .x))
    abundanceExport
}
